server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db

spring.kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: product-group
    auto-offset-reset: earliest

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.config.activate.on-profile: docker

server.port: 8080

spring.data.mongodb.host: mongodb

---
spring.config.activate.on-profile: kafka

spring.kafka.bootstrap-servers: kafka:9092

---
spring.config.activate.on-profile: crac

server.port: 8080

spring.data.mongodb.host: mongodb

# See https://github.com/spring-projects/spring-lifecycle-smoke-tests/tree/main/data/data-mongodb
spring.data.mongodb.auto-index-creation: false

spring:
  application.name: product
  cloud.refresh.extra-refreshable:
    - com.mongodb.reactivestreams.client.MongoClient
  config.import: file:./runtime-configuration.yml

management.endpoints.web.exposure.include:
  - refresh
  - health
  - env
