# syntax=docker/dockerfile:1.3-labs
# The above syntax directive is required to get support for "RUN --security=insecure"

# Does not work starting with azul/zulu-openjdk:21.0.4-21.36-jdk-crac, error message:
# - Error (criu/cr-restore.c:1518): Can't fork for 7: Read-only file system
# - Error (criu/cr-restore.c:2605): Restoring FAILED.
# - Error (criu/cr-restore.c:1835): Pid 13 do not match expected 7
# FROM azul/zulu-openjdk:21-jdk-crac AS builder

FROM azul/zulu-openjdk:21.0.3-21.34-jdk-crac AS builder

RUN apt update && apt-get install curl jq -y

ADD build/libs/*.jar app.jar
ADD crac/checkpoint-on-demand.bash checkpoint-on-demand.bash

# The file must exist while performing the checkpoint
RUN touch runtime-configuration.yml

# The crac profile is only required for the review service. Do we need the other crac profiles???
RUN --security=insecure SPRING_PROFILES_ACTIVE=crac JAR_FILE=app.jar OUT_FOLDER=./checkpoint ./checkpoint-on-demand.bash

FROM azul/zulu-openjdk:21.0.3-21.34-jdk-crac AS runtime

COPY --from=builder checkpoint checkpoint
COPY --from=builder app.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-XX:CRaCRestoreFrom=checkpoint"]
